# Generated by Django 4.2.2 on 2023-06-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduzca el nombre del director.', max_length=64)),
                ('biography', models.TextField(help_text='Introduzca la biografía del director.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreFilm', models.CharField(help_text='Introduzca el género de la pelicula.', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Introduzca el nombre de la película.', max_length=64)),
                ('year', models.IntegerField(help_text='Introduzca el año que se estrenó', max_length=4)),
                ('duration', models.IntegerField(help_text='Introduzca los minutos que dura la película', max_length=16)),
                ('synopsis', models.TextField(help_text='Sinopsis de la película.', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directores.director')),
                ('genre', models.ManyToManyField(to='directores.genre')),
            ],
        ),
    ]
