# Generated by Django 4.2.2 on 2023-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.IntegerField(help_text='Introduzca los minutos que dura la película'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(help_text='Introduzca el año que se estrenó'),
        ),
    ]
