# Generated by Django 4.2.2 on 2023-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0004_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(help_text='Seleccione uno o varios géneros.', to='directores.genre'),
        ),
    ]
